package IssueManagement;
// Generated Nov 16, 2015 9:40:26 AM by Hibernate Tools 4.3.1


import HibernateSettings.HibernateUtil;
import UserManagement.User;
import common.VenusSession;
import java.util.ArrayList;
import proman.Project;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Session;
import org.hibernate.Query;
import org.hibernate.Transaction;
/**
 * Issue generated by hbm2java
 */
public class Issue  implements java.io.Serializable {


     private int id;
     private Project project;
     private User userByAssignee;
     private User userByCreatoruserId;
     private String summary;
     private String description;
     private Date creationDate;
     private Date updateDate;
     private String type;
     private String status;
     private Integer priority;
     private Date dueDate;
     private Set attachments = new HashSet(0);
     private Set issuehistories = new HashSet(0);
     private Set comments = new HashSet(0);

    public Issue() {
    }

	
    public Issue(int id, Project project,User userByAssignee) {
        this.id = id;
        this.project = project;
        this.userByAssignee = userByAssignee;
    }
    public Issue(int id, Project project,User userByAssignee,User userByCreatoruserId, String summary, String description, Date creationDate, Date updateDate, String type, String status, Integer priority, Date dueDate, Set attachments, Set issuehistories, Set comments) {
       this.id = id;
       this.project = project;
       this.userByAssignee = userByAssignee;
       this.userByCreatoruserId = userByCreatoruserId;
       this.summary = summary;
       this.description = description;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
       this.type = type;
       this.status = status;
       this.priority = priority;
       this.dueDate = dueDate;
       this.attachments = attachments;
       this.issuehistories = issuehistories;
       this.comments = comments;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public User getUserByAssignee() {
        return this.userByAssignee;
    }
    
    public void setUserByAssignee(User userByAssignee) {
        this.userByAssignee = userByAssignee;
    }
    public User getUserByCreatoruserId() {
        return this.userByCreatoruserId;
    }
    
    public void setUserByCreatoruserId (User userByCreatoruserId) {
        this.userByCreatoruserId = userByCreatoruserId;
    }
    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Set getAttachments() {
        return this.attachments;
    }
    
    public void setAttachments(Set attachments) {
        this.attachments = attachments;
    }
    public Set getIssuehistories() {
        return this.issuehistories;
    }
    
    public void setIssuehistories(Set issuehistories) {
        this.issuehistories = issuehistories;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }

   public void saveIssue(){
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.save(this);
        session.getTransaction().commit();
   }

   public List getAllIssueTypes(){
       List l = new ArrayList();
       
       l.add("Bug");
       l.add("Task");
       
       return l;
   }
   public List getAllPriorityTypes(){
       List list = new ArrayList();
       
       list.add("Major");
       list.add("Minor");
       
       return list;
   }
  
    public List getAllIssue(){
        
        System.out.print("asdadsadasdsd");
        
       Session session = HibernateUtil.getSessionFactory().openSession();
        
        User loggedInUser = VenusSession.getSession().getUser();
        Transaction transaction;
        transaction=session.beginTransaction();
        Query query = session.createQuery("from IssueManagement.Issue u where u.userByAssignee.id = :userid");
        query.setParameter("userid", loggedInUser.getId());
         
        List<Issue> listt = query.list();
        transaction.commit();
        session.close();
        
        System.out.println(listt); 
    
    
        return listt;
    }
}


