package IssueManagement;

import HibernateSettings.HibernateUtil;
 import java.io.IOException;
 import java.io.InputStream;
 import java.util.Scanner;
 import javax.servlet.http.Part;
import IssueManagement.Issue;
import UserManagement.User;
import java.util.Date;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Attachment generated by Sema Yıldırım
 */
public class Attachment  implements java.io.Serializable {


     private Integer id;
     private Issue issue;
     private String documentpath;
     private Date creationDate;
     private Part uploadedFile;
private String text;

    public Attachment() {
    }

	public void upload() {

        if (null != getUploadedFile()) {
            try {
                InputStream is = getUploadedFile().getInputStream();
                
                setText(new Scanner(is).useDelimiter("\\A").next());
            } catch (IOException ex) {
            }
        }
    }
    public Attachment(Issue issue) {
        this.issue = issue;
    }
    public Attachment(Issue issue, String documentpath, Date creationDate) {
       this.issue = issue;
       this.documentpath = documentpath;
       this.creationDate = creationDate;
    }
    void save() {
   Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.save(this);
        session.getTransaction().commit();
    
    }
    public List<Attachment> getAttachmentDetail(int id){
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.getTransaction().commit();
        Transaction tx;
        tx=session.beginTransaction();
        Query query = session.createQuery("from IssueManagement.Attachment where issue_id= :idd");
        query.setParameter("idd", id);
        List<Attachment> attach=query.list();
        
        return attach;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getDocumentpath() {
        return this.documentpath;
    }
    
    public void setDocumentpath(String documentpath) {
        this.documentpath = documentpath;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * @return the uploadedFile
     */
    public Part getUploadedFile() {
        return uploadedFile;
    }

    /**
     * @param uploadedFile the uploadedFile to set
     */
    public void setUploadedFile(Part uploadedFile) {
        this.uploadedFile = uploadedFile;
    }

    /**
     * @return the text
     */
    public String getText() {
        return text;
    }

    /**
     * @param text the text to set
     */
    public void setText(String text) {
        this.text = text;
    }

    




}


