package IssueManagement;


import HibernateSettings.HibernateUtil;
import IssueManagement.Issue;
import java.util.Date;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import proman.Project;

/**
 * Comment generated by Sema Yıldırım
 */
public class Comment  implements java.io.Serializable {


     private Integer id;
     private Issue issue;
     private Date creationDate;
     private String comment;
     private List<Comment> list;

    public Comment() {
    }

	
    public Comment(Issue issue) {
        this.issue = issue;
    }
    public Comment(Issue issue, Date creationDate, String comment) {
       this.issue = issue;
       this.creationDate = creationDate;
       this.comment = comment;
    }
    public void saveComment(){
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.save(this);
        session.getTransaction().commit();
   }
   public List<Comment> getComment(int id){
       Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction(); 
        session.getTransaction().commit();
        Transaction tx;
        tx=session.beginTransaction();
        Query query = session.createQuery("from IssueManagement.Comment where issue_id= :id");
        query.setParameter("id", id);
        setList((List<Comment>) query.list());
        tx.commit();
        session.close();
        return getList();
   }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * @return the list
     */
    public List<Comment> getList() {
        return list;
    }

    /**
     * @param list the list to set
     */
    public void setList(List<Comment> list) {
        this.list = list;
    }




}


