package IssueManagement;
// Generated Dec 6, 2015 9:28:16 PM by Hibernate Tools 4.3.1


import UserManagement.User;
import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer id;
     private Issue issue;
     private User user;
     private Date creationDate;
     private String comment;
     private String creatorName;

    public Comment() {
    }

	
    public Comment(Issue issue, User user) {
        this.issue = issue;
        this.user = user;
    }
    public Comment(Issue issue, User user, Date creationDate, String comment, String creatorName) {
       this.issue = issue;
       this.user = user;
       this.creationDate = creationDate;
       this.comment = comment;
       this.creatorName = creatorName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getCreatorName() {
        return this.creatorName;
    }
    
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName;
    }




}


