package IssueManagement;



/**
 * IssueId generated by Sema Yıldırım
 */
public class IssueId  implements java.io.Serializable {


     private int id;
     private int projectId;
     private int assignee;

    public IssueId() {
    }

    public IssueId(int id, int projectId, int assignee) {
       this.id = id;
       this.projectId = projectId;
       this.assignee = assignee;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }
    public int getAssignee() {
        return this.assignee;
    }
    
    public void setAssignee(int assignee) {
        this.assignee = assignee;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IssueId) ) return false;
		 IssueId castOther = ( IssueId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getProjectId()==castOther.getProjectId())
 && (this.getAssignee()==castOther.getAssignee());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getProjectId();
         result = 37 * result + this.getAssignee();
         return result;
   }   


}


