package DAO;
// Generated Nov 22, 2015 7:35:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer id;
     private Issue issue;
     private Date creationDate;
     private String comment;

    public Comment() {
    }

	
    public Comment(Issue issue) {
        this.issue = issue;
    }
    public Comment(Issue issue, Date creationDate, String comment) {
       this.issue = issue;
       this.creationDate = creationDate;
       this.comment = comment;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


