package DAO;
// Generated Nov 22, 2015 7:35:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Issuehistory generated by hbm2java
 */
public class Issuehistory  implements java.io.Serializable {


     private IssuehistoryId id;
     private Issue issue;
     private User user;
     private Date updateDate;

    public Issuehistory() {
    }

	
    public Issuehistory(IssuehistoryId id, Issue issue, User user) {
        this.id = id;
        this.issue = issue;
        this.user = user;
    }
    public Issuehistory(IssuehistoryId id, Issue issue, User user, Date updateDate) {
       this.id = id;
       this.issue = issue;
       this.user = user;
       this.updateDate = updateDate;
    }
   
    public IssuehistoryId getId() {
        return this.id;
    }
    
    public void setId(IssuehistoryId id) {
        this.id = id;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


