package DAO;
// Generated Nov 22, 2015 7:35:56 PM by Hibernate Tools 4.3.1



/**
 * IssuehistoryId generated by hbm2java
 */
public class IssuehistoryId  implements java.io.Serializable {


     private int id;
     private int userId;

    public IssuehistoryId() {
    }

    public IssuehistoryId(int id, int userId) {
       this.id = id;
       this.userId = userId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IssuehistoryId) ) return false;
		 IssuehistoryId castOther = ( IssuehistoryId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


