package IssueManagement;
// Generated Nov 16, 2015 9:40:26 AM by Hibernate Tools 4.3.1


import IssueManagement.Issue;
import java.util.Date;

/**
 * Attachment generated by hbm2java
 */
public class Attachment  implements java.io.Serializable {


     private Integer id;
     private Issue issue;
     private String documentpath;
     private Date creationDate;

    public Attachment() {
    }

	
    public Attachment(Issue issue) {
        this.issue = issue;
    }
    public Attachment(Issue issue, String documentpath, Date creationDate) {
       this.issue = issue;
       this.documentpath = documentpath;
       this.creationDate = creationDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getDocumentpath() {
        return this.documentpath;
    }
    
    public void setDocumentpath(String documentpath) {
        this.documentpath = documentpath;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }




}


